openapi: '3.0.1'
info:
  title: Cadastro de Medicamentos
  description: >
    Gerenciador de estoque de medicamentos em farmacia.
  version: '0.2'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'
paths:
  /medicamentos:
    get:
      summary: Listar medicamentos
      responses:
        200:
          description: Lista de medicamentos
    
    post:
      summary: Criar um medicamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do medicamento.
                  example: Dipirona
                comprimidos:
                  type: string
                  description: Quantidade de comprimidos
                  example: 30
                unidade_medida:
                  type: string
                  description: Unidade de medida do medicamento em miligramas.
                  example: 1000mg
      responses:
        201:
          description: Medicamento criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: URI do novo recurso criado.
        400:
          description: Requisição inválida
    
  /medicamentos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Obter um medicamento
      responses:
        200:
          description: Medicamento encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nome:
                    type: string
                  laboratorio:
                    type: string
                  fornecedor:
                    type: string
                  unidade_medida:
                    type: string
        404:
          description: Não encontrado.
          
    delete:
      summary: Apagar um medicamento
      responses:
        200:
          description: Medicamento apagado
        404:
          description: Não encontrado.
      
    put:
      summary: Atualizar um medicamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do medicamento.
                  example: Rivotril
                comprimidos:
                  type: string
                  description: Quantidade de comprimidos
                  example: 30
                unidade_medida:
                  type: string
                  description: Unidade de medida do medicamento em miligramas.
                  example: 2,5mg
      responses:
        200:
          description: Medicamento atualizado
        404:
          description: Não encontrado.

  /relatorios:
    get:
      summary: Gerar relatório de medicamentos
      parameters:
        - name: tipo
          in: query
          description: Tipo de relatório (diário, semanal, mensal ou intervalo personalizado).
          required: true
          schema:
            type: string
            enum:
              - diario
              - semanal
              - mensal
              - intervalo
        - name: data_inicio
          in: query
          description: Data de início do intervalo (obrigatório para tipo "intervalo").
          required: false
          schema:
            type: string
            format: date
            example: 2024-01-01
        - name: data_fim
          in: query
          description: Data de término do intervalo (obrigatório para tipo "intervalo").
          required: false
          schema:
            type: string
            format: date
            example: 2024-01-31
      responses:
        200:
          description: Relatório gerado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  tipo:
                    type: string
                    description: Tipo de relatório gerado.
                  periodo:
                    type: object
                    properties:
                      inicio:
                        type: string
                        format: date
                        description: Data de início do período.
                      fim:
                        type: string
                        format: date
                        description: Data de fim do período.
                  medicamentos:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nome:
                          type: string
                        quantidade_total:
                          type: integer
                        unidade_medida:
                          type: string
        400:
          description: "Requisição inválida (ex.: parâmetros ausentes ou tipo inválido)."
