openapi: '3.0.1'
info:
  title: Cadastro de Medicamentos
  description: >
    Gerenciador de estoque de medicamentos em farmácia.
  version: '0.2'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'
paths:
  /medicamentos:
    get:
      summary: Listar medicamentos
      responses:
        200:
          description: Lista de medicamentos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nome:
                      type: string
                    laboratorio:
                      type: string
                    fornecedor:
                      type: string
                    medida:
                      type: string
                    quantidade:
                      type: integer
                    mg:
                      type: integer
    
    post:
      summary: Criar um medicamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do medicamento.
                  example: Dipirona
                laboratorio:
                  type: string
                  description: Nome do laboratório responsável.
                  example: Teuto
                fornecedor:
                  type: string
                  description: Nome do fornecedor.
                  example: Drogaria Center Cruzeta
                medida:
                  type: string
                  description: Tipo da unidade de medida (caixa, frasco, cartela).
                  example: caixa
                quantidade:
                  type: integer
                  description: Quantidade de unidades na medida.
                  example: 20
                mg:
                  type: integer
                  description: Quantidade em miligramas por unidade.
                  example: 500
      responses:
        201:
          description: Medicamento criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: URI do novo recurso criado.
        400:
          description: Requisição inválida
    
  /medicamentos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Obter um medicamento
      responses:
        200:
          description: Medicamento encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nome:
                    type: string
                  laboratorio:
                    type: string
                  fornecedor:
                    type: string
                  medida:
                    type: string
                  quantidade:
                    type: integer
                  mg:
                    type: integer
        404:
          description: Não encontrado.
          
    delete:
      summary: Apagar um medicamento
      responses:
        200:
          description: Medicamento apagado
        404:
          description: Não encontrado.
      
    put:
      summary: Atualizar um medicamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do medicamento.
                  example: Rivotril
                laboratorio:
                  type: string
                  description: Nome do laboratório responsável.
                  example: Biopas
                fornecedor:
                  type: string
                  description: Nome do fornecedor.
                  example: Drogaria Center Cruzeta
                medida:
                  type: string
                  description: Tipo da unidade de medida (caixa, frasco, cartela).
                  example: cartela
                quantidade:
                  type: integer
                  description: Quantidade de unidades na medida.
                  example: 15
                mg:
                  type: integer
                  description: Quantidade em miligramas por unidade.
                  example: 2.5
      responses:
        200:
          description: Medicamento atualizado
        404:
          description: Não encontrado.
